# Generated by Django 3.2.7 on 2021-09-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='task',
            name='subject',
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
